
version: '3.8'

services:

  backend:
    image: webbylabhub/movies  
    container_name: backend-server 
    ports:
      - "8000:8000" 
    restart: always 

  frontend:

    build: .
    container_name: frontend-app
    ports:
      - "3000:3000" 
    

    depends_on:
      - backend

    environment:

      - API_URL=http://backend:8000/api/v1
      - USER_EMAIL=test1753282520585@gmail.com
      - USER_PASSWORD=password1111           